### ISSUE TITLE
player 회전 관련 코드 보완

### ISSUE THREAD

**Issue by YangHun** [aborile/group-study#1]

**Comment by aborile** [comment]
velocity의 x와 z의 벡터합 길이가 일정하도록 코드 수정.

-> x의 범위에 제한을 두어 최대 초기 방향에서 수직으로 꺾인 방향으로까지 (|x| = 최대, z = 0) 움직일 수 있게 해두었는데, 너무 제한을 크게 둔건가 싶습니다. :3c
