### ISSUE TITLE
map generator (1) parser

### ISSUE THREAD

**Issue by YangHun** [aborile/group-study#2]
- 파서 리서치 : C# 파일 입출력, string
- 파싱 데이터 규칙 만들기
- 파서 클래스 만들기 (monobehaviour 상속)

**Comment by YangHun** [comment]
참고 : obj file format

**Comment by aborile** [comment]
- 데이터 규칙: 0 타일 없음, 1 일반 타일, 2 초기 타일
- map.txt파일을 읽어 그 안에 담긴 내용을 List에 저장하는 부분까지 만들었습니다.
  (각 줄마다 7개의 숫자가 담긴 txt > 각 줄의 숫자들을 string []에 저장 > 저장한 string []을 List에 저장)
